# Generated by Django 3.2 on 2023-01-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20221225_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='College',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='app1.college'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='College',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='app1.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjs', to='app1.department'),
        ),
    ]
